spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: DBUserName
    password: DBPassword
    url: jdbc:oracle:thin:@//host:port/dbname





